### ISSUE TITLE
Improve workflow for case where dependency manager is not present.

### ISSUE THREAD

**Issue by abclay** [tetrascience/ts-data-insights-ci-cd-common#2]
Should you also install from requirements.txt if it exists before testing?  Alternatively, should we fail a build if it's missing files for the two dependency management tools we use?

_Originally posted by @mlipschultz in https://github.com/tetrascience/ts-data-insights-ci-cd-common/pull/1#discussion_r792980273_

**Comment by VladimirShteyn** [comment]
> In the longer term, I would very much like to build artifacts from a `pipfile.lock` or `poetry.lock` file instead of `requirements.txt`. That way we know we're using the same instances of dependencies in dev/test/prod. There may be some complications with that, such as cross-platform dev and working within the codebuild/ABS framework, but I think we can work through those.

Implemented (except for the case of SSP)! @abclay feel free to close.
